/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-05-14 05:39:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Reporte_005fde_005fBienes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("\tintegrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\t\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".fondonavsup{\r\n");
      out.write("background-image: radial-gradient(circle at 119.64% 37.72%, #18344a 0, #010912 50%, #000000 100%);\r\n");
      out.write("}\r\n");
      out.write(".fondonavbody{\r\n");
      out.write("background-image: radial-gradient(circle at 119.64% 37.72%, #204177 0, #021a39 50%, #000000 100%);\r\n");
      out.write("}\r\n");
      out.write(".men {\r\n");
      out.write("\tbackground: green;\r\n");
      out.write("\tpadding: 2px;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write(".navbar-brand__sup {\r\n");
      out.write("width: 220px;\r\n");
      out.write("height: 70px;\r\n");
      out.write("}\r\n");
      out.write(".navbar-brand__brand {\r\n");
      out.write("width: 50px;\r\n");
      out.write("}\r\n");
      out.write(".navbar-brand__icon {\r\n");
      out.write("width: 50px;\r\n");
      out.write("height: 50px;\r\n");
      out.write("align-self: center;\r\n");
      out.write("}\r\n");
      out.write(".marg-top {\r\n");
      out.write("\tmargin-top: 95px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar sticky-top navbar-dark fondonavsup justify-content-between\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"d-flex d-content-start\">\r\n");
      out.write("\t\t\t\t<!--Brand-->\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"navbar-brand d-flex\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"imagenes/MinisteriPublico.svg\" all=\"we share\" loading=\"lazy\"\r\n");
      out.write("\t\t\t\t\tclass=\"navbar-brand__sup text-light\"/>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler navbar-brand__icon\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\"\r\n");
      out.write("\t\t\t\t\taria-controls=\"offcanvasNavbar\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-home text-light\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"d-flex d-content-between\">\r\n");
      out.write("\t\t\t\t<img src=\"imagenes/usuario.png\" all=\"we share\" loading=\"lazy\"\r\n");
      out.write("\t\t\t\t\tclass=\"navbar-brand__brand rounded-circle bg-light tabindex-80\" />\r\n");
      out.write("\t\t\t\t<li class=\"navbar dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link navbar-brand dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\tid=\"offcanvasNavbarDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-bs-toggle=\"dropdown\" aria-expanded=\"false\"> Usuario </a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-dark fondonavsup\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"offcanvasNavbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Nelson</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Alfredo</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Edith</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Franco</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Jorge</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Eduardo</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"offcanvas offcanvas-start marg-top\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\tid=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\"\r\n");
      out.write("\t\t\t\tdata-bs-scroll=\"true\" data-bs-backdrop=\"true\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"offcanvas-body fondonavsup\" tabindex=\"-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav flex-grow-1 pe-3 navbar-brand\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle d-block\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"offcanvasNavbarDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-boxes text-light me-3\"></i>Mantenimiento </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-dark fondonavsup\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"offcanvasNavbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Registro de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tBienes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Registro de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tProveedores</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Registro de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tDevoluciones</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Registro de Orden\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tde Compra</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Otros</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown p-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"offcanvasNavbarDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-truck-loading text-light me-3\"></i>Movimientos </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-dark fondonavsup\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"offcanvasNavbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Ingresos de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAlmacén</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Egresos de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAlmacén</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Otros</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown p-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"offcanvasNavbarDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-dna text-light me-3\"></i>Consultar </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-dark fondonavsup\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"offcanvasNavbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Consulta 01</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Consulta 02</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Otros</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown p-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"offcanvasNavbarDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-barcode text-light me-3\"></i>Reporte </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-dark fondonavsup\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"offcanvasNavbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Reporte 01</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Reporte 02</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Otros</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown pe-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"offcanvasNavbarDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-users text-light me-3\"></i> Nosotros\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-dark fondonavsup\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"offcanvasNavbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Misión</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Visión</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Otros</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"text-center mt-5\">Reporte de Bienes<img src=\"imagenes/repor.png\" class=\"img-thumbnail\" width=\"100\" height=\"70\"class=\"d-inline-block align-text-top\"></h1>\r\n");
      out.write("\t\t\t<br>\t\r\n");
      out.write("\t<div class=\"mt-4\">\r\n");
      out.write("\t\t\t<table id=\"example\" class=\"table table-striped\" style=\"width:100%\">\r\n");
      out.write("\t\t        <thead>\r\n");
      out.write("\t\t            <tr class=\"table-success\">\r\n");
      out.write("\t\t                <th>Código</th>\r\n");
      out.write("\t\t                <th>Tipo de Bienes</th>\r\n");
      out.write("\t\t                <th>Nombre de Bienes</th>\r\n");
      out.write("\t\t                <th>Precio de Compra</th>\r\n");
      out.write("\t\t                <th>Cantidad</th>\r\n");
      out.write("\t\t                <th>Descripción</th>\r\n");
      out.write("\t\t                <th>Estado</th>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t        </thead>\r\n");
      out.write("\t\t         <tbody>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>C00001</td>\r\n");
      out.write("\t\t                <td>Escritorio</td>\r\n");
      out.write("\t\t                <td>Lapiceros</td>\r\n");
      out.write("\t\t                <td>$320,800</td>\r\n");
      out.write("\t\t                <td>1000</td>\r\n");
      out.write("\t\t                <td>Tinta fina Azul</td>\r\n");
      out.write("\t\t                <td>nuevo</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t          </tbody>\r\n");
      out.write("\t \t\t\t\r\n");
      out.write("\t\t         <tfoot>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>Código</th>\r\n");
      out.write("\t\t                <th>Tipo de Bienes</th>\r\n");
      out.write("\t\t                <th>Nombre de Bienes</th>\r\n");
      out.write("\t\t                <th>Precio de Compra</th>\r\n");
      out.write("\t\t                <th>Cantidad</th>\r\n");
      out.write("\t\t                <th>Descripción</th>\r\n");
      out.write("\t\t                <th>Estado</th>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t        </tfoot>\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t<div class=\"d-grid gap-2 d-md-flex justify-content-md-end\"> <button type=\"button\"  class=\"btn btn-outline-secondary\">Cerrar</button></div>\r\n");
      out.write("\t<br>\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("\t<footer class=\"sticky-button text-center text-white\" style=\"background-image: radial-gradient(circle at 119.64% 37.72%, #18344a 0, #010912 50%, #000000 100%);\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t <div class=\"container p-4\" >\r\n");
      out.write("   \r\n");
      out.write("\t     <div class=\"row fs-6\">\r\n");
      out.write("\t       <div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("\t\t        <h5 class=\"text-uppercase\">UBICACIÓN</h5>\r\n");
      out.write("\t\t       <p>\r\n");
      out.write("\t\t          Av. Abancay 5, <br>\r\n");
      out.write("\t\t          Cercado de Lima 15001 \r\n");
      out.write("\t\t        </p>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\t  <div class=\"col-lg-6 mb-12 mb-lg-0\">     \r\n");
      out.write("\t\t\t    <!-- Section: Social media -->\r\n");
      out.write("\t\t\t    <section class=\"mb-4\">\r\n");
      out.write("\t\t\t    <h4>Ministerio Público - Fiscalía de la Nación 2022</h4>\r\n");
      out.write("\t\t\t      <br>\r\n");
      out.write("\t\t\t      <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://es-la.facebook.com/\"><i class=\"fab fa-fw fa-facebook-f\"></i></a>\r\n");
      out.write("\t\t          <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://twitter.com/\"><i class=\"fab fa-fw fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t      <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://www.youtube.com/\"><i class=\"fab fa-fw fa-youtube\"></i></a>\r\n");
      out.write("\t\t\t    </section>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t      <!--Grid column-->\r\n");
      out.write("\t       <div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("\t\t        <h5 class=\"text-uppercase\">CONTACTO</h5>\r\n");
      out.write("\t\t        <p>\r\n");
      out.write("\t\t          Central Telefónica: <br>\r\n");
      out.write("\t\t          625-5555<br>\r\n");
      out.write("\t\t\t\t  Línea Gratuita:<br>\r\n");
      out.write("\t\t\t\t  0-800-00-205\r\n");
      out.write("\t\t\t    </p>\r\n");
      out.write("\t\t  </div> \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t\t  <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.2);\">\r\n");
      out.write("\t\t    © Derechos Reservados\r\n");
      out.write("\t  \t  </div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JS para validación-->\r\n");
      out.write("<script src=\"https://cdn.bootcdn.net/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#example').DataTable();\r\n");
      out.write("} );\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
